model_name_or_path: "/home/kashurin/.cache/huggingface/hub/models--t-tech--T-lite-it-1.0/snapshots/fbabc76f32140416dc5b0ceef392c7778eec1312/" 
dataset: "/home/kashurin/.local/Grounded-RAG-RU-v2"
train_only_on_completions: True
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
# num_train_epochs: 1
max_steps: 60
save_strategy: "steps"
save_steps: 30
save_total_limit: 6
learning_rate: 0.00004
gradient_accumulation_steps: 8
gradient_checkpointing: True
logging_steps: 1
remove_unused_columns: True
dataloader_num_workers: 2
generate_eval_examples: True
eval_strategy: "steps"
eval_steps: 10

run_name: "sft-grag-llama-3.1-unsloth-lora-32-qkvo"
output_dir: "/home/kashurin/.local/models/sft-grag-llama-3.1-unsloth-lora-32-qkvo"
warmup_steps: 20
report_to: "none"
conversation_field: "conversation"
optim: "adamw_8bit"
bf16: True
seed: 42
logging_first_step: True
use_peft: True
lora_target_modules:
  - "k_proj"
  - "v_proj"
  - "q_proj"
  - "o_proj"
lora_r: 16
lora_alpha: 16
assistant_message_template: "<|start_header_id|>assistant<|end_header_id|>"
eos_token: "<|eot_id|>"
chat_template: "{{ bos_token }}{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
force_chat_template: True
